"""add colm user role in user tbl

Revision ID: 4075375ad61c
Revises: 439368655346
Create Date: 2026-02-14 19:59:05.987196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4075375ad61c'
down_revision: Union[str, Sequence[str], None] = '439368655346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")

    op.alter_column(
        'users',
        'role',
        nullable=False,
        server_default=None
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
